/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CourierAgentService } from "../courierAgent.service";
import { CourierAgentCreateInput } from "./CourierAgentCreateInput";
import { CourierAgent } from "./CourierAgent";
import { CourierAgentFindManyArgs } from "./CourierAgentFindManyArgs";
import { CourierAgentWhereUniqueInput } from "./CourierAgentWhereUniqueInput";
import { CourierAgentUpdateInput } from "./CourierAgentUpdateInput";
import { DeliveryFindManyArgs } from "../../delivery/base/DeliveryFindManyArgs";
import { Delivery } from "../../delivery/base/Delivery";
import { DeliveryWhereUniqueInput } from "../../delivery/base/DeliveryWhereUniqueInput";

export class CourierAgentControllerBase {
  constructor(protected readonly service: CourierAgentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CourierAgent })
  async createCourierAgent(
    @common.Body() data: CourierAgentCreateInput
  ): Promise<CourierAgent> {
    return await this.service.createCourierAgent({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CourierAgent] })
  @ApiNestedQuery(CourierAgentFindManyArgs)
  async courierAgents(@common.Req() request: Request): Promise<CourierAgent[]> {
    const args = plainToClass(CourierAgentFindManyArgs, request.query);
    return this.service.courierAgents({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CourierAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async courierAgent(
    @common.Param() params: CourierAgentWhereUniqueInput
  ): Promise<CourierAgent | null> {
    const result = await this.service.courierAgent({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CourierAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCourierAgent(
    @common.Param() params: CourierAgentWhereUniqueInput,
    @common.Body() data: CourierAgentUpdateInput
  ): Promise<CourierAgent | null> {
    try {
      return await this.service.updateCourierAgent({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CourierAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCourierAgent(
    @common.Param() params: CourierAgentWhereUniqueInput
  ): Promise<CourierAgent | null> {
    try {
      return await this.service.deleteCourierAgent({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/deliveries")
  @ApiNestedQuery(DeliveryFindManyArgs)
  async findDeliveries(
    @common.Req() request: Request,
    @common.Param() params: CourierAgentWhereUniqueInput
  ): Promise<Delivery[]> {
    const query = plainToClass(DeliveryFindManyArgs, request.query);
    const results = await this.service.findDeliveries(params.id, {
      ...query,
      select: {
        courierAgent: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        order: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/deliveries")
  async connectDeliveries(
    @common.Param() params: CourierAgentWhereUniqueInput,
    @common.Body() body: DeliveryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveries: {
        connect: body,
      },
    };
    await this.service.updateCourierAgent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/deliveries")
  async updateDeliveries(
    @common.Param() params: CourierAgentWhereUniqueInput,
    @common.Body() body: DeliveryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveries: {
        set: body,
      },
    };
    await this.service.updateCourierAgent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/deliveries")
  async disconnectDeliveries(
    @common.Param() params: CourierAgentWhereUniqueInput,
    @common.Body() body: DeliveryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveries: {
        disconnect: body,
      },
    };
    await this.service.updateCourierAgent({
      where: params,
      data,
      select: { id: true },
    });
  }
}
